%
Aldi = {...
        {NK_KT_S       ,           1};     ...
        {NK_KR_V       ,           1};     ...
        {TK_TKT_S      ,           1};     ...
        {NK_KZ         ,           1};     ...
        {TK_KZ         ,           1}      ...
       };

% Aldi = {...
%         { NK_KT_S	,	1}     ...
%        };
