%%
%%       Kind of fridge,           number of fridges
% Aldi = {...
%         { NK_KT_S	,	1};     ...
%         { NK_KR_V	,	1};     ...
%         { TK_TKT_S	, 	1}      ...
%        };
Aldi = {...
        { NK_KT_S	,	4}     ...
       };
