%% The conf.m file have to be in this format for make the program run.
%%         Bus,  Supermarkets,           Anzahl des Supermarkets
config_grid_ = {...
	    1 , {Aldi        ,        1500};     ...
	    2 , {0           ,           0};     ...
	    3 , {0           ,           0};     ...
	    4 , {0           ,           0}      ...
	      };
